[package]
name = "kaleidoscope_compiler"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.23.0"

[dependencies]
logos = "0.16.1"
lalrpop-util = { version = "0.23.0" }
inkwell = { version = "0.8.0", features = ["llvm20-1"] }
